Sitegeist:
  ZombieHunt:

    # hidden nodes turn into zombies after this period
    zombificationPeriod: 60

    # zombie-nodes start are due to destruction after this period
    destructionPeriod: 120

    # the label for zombie-nodes
    zombieLabel: '🧟'

    # label for zombie-nodes that are due to destruction
    zombieToDestroyLabel: '🔥🧟🔥'

Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.ZombieHunt: true
  Fusion:
    defaultContext:
      Sitegeist.ZombieHunt.ZombieDetector: 'Sitegeist\ZombieHunt\Helper\ZombieDetectorHelper'
